# Generated by Django 3.1.2 on 2021-01-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.CharField(choices=[('Not processed', 'Not processed'), ('Out on delivery', 'Out on delivery')], default='Not processed', max_length=200),
        ),
    ]
