# Generated by Django 3.1.2 on 2021-01-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0002_order_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.CharField(choices=[['Not processed', 'Not processed'], ['Out on delivery', 'Out on delivery']], default='Not processed', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
