# Generated by Django 3.1.2 on 2021-02-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0003_auto_20210130_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'date'},
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
