# Generated by Django 3.1.2 on 2021-02-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0004_auto_20210205_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
